// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessgae.proto

package com.bayss.common.netty.proto;

public final class ProtoMessgae {
  private ProtoMessgae() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageeHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bayss.common.netty.proto.MessageeHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>uint32 magic_num = 2;</code>
     * @return The magicNum.
     */
    int getMagicNum();

    /**
     * <code>uint32 cmd = 3;</code>
     * @return The cmd.
     */
    int getCmd();

    /**
     * <code>uint32 len = 4;</code>
     * @return The len.
     */
    int getLen();

    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.bayss.common.netty.proto.MessageeHeader}
   */
  public static final class MessageeHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bayss.common.netty.proto.MessageeHeader)
      MessageeHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageeHeader.newBuilder() to construct.
    private MessageeHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageeHeader() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageeHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageeHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 16: {

              magicNum_ = input.readUInt32();
              break;
            }
            case 24: {

              cmd_ = input.readUInt32();
              break;
            }
            case 32: {

              len_ = input.readUInt32();
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bayss.common.netty.proto.ProtoMessgae.internal_static_com_bayss_common_netty_proto_MessageeHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bayss.common.netty.proto.ProtoMessgae.internal_static_com_bayss_common_netty_proto_MessageeHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.class, com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>uint32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int MAGIC_NUM_FIELD_NUMBER = 2;
    private int magicNum_;
    /**
     * <code>uint32 magic_num = 2;</code>
     * @return The magicNum.
     */
    @java.lang.Override
    public int getMagicNum() {
      return magicNum_;
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <code>uint32 cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public int getCmd() {
      return cmd_;
    }

    public static final int LEN_FIELD_NUMBER = 4;
    private int len_;
    /**
     * <code>uint32 len = 4;</code>
     * @return The len.
     */
    @java.lang.Override
    public int getLen() {
      return len_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (magicNum_ != 0) {
        output.writeUInt32(2, magicNum_);
      }
      if (cmd_ != 0) {
        output.writeUInt32(3, cmd_);
      }
      if (len_ != 0) {
        output.writeUInt32(4, len_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (magicNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, magicNum_);
      }
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, cmd_);
      }
      if (len_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, len_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader)) {
        return super.equals(obj);
      }
      com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader other = (com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getMagicNum()
          != other.getMagicNum()) return false;
      if (getCmd()
          != other.getCmd()) return false;
      if (getLen()
          != other.getLen()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + MAGIC_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getMagicNum();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + LEN_FIELD_NUMBER;
      hash = (53 * hash) + getLen();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bayss.common.netty.proto.MessageeHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bayss.common.netty.proto.MessageeHeader)
        com.bayss.common.netty.proto.ProtoMessgae.MessageeHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bayss.common.netty.proto.ProtoMessgae.internal_static_com_bayss_common_netty_proto_MessageeHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bayss.common.netty.proto.ProtoMessgae.internal_static_com_bayss_common_netty_proto_MessageeHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.class, com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.Builder.class);
      }

      // Construct using com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        magicNum_ = 0;

        cmd_ = 0;

        len_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bayss.common.netty.proto.ProtoMessgae.internal_static_com_bayss_common_netty_proto_MessageeHeader_descriptor;
      }

      @java.lang.Override
      public com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader getDefaultInstanceForType() {
        return com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader build() {
        com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader buildPartial() {
        com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader result = new com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader(this);
        result.version_ = version_;
        result.magicNum_ = magicNum_;
        result.cmd_ = cmd_;
        result.len_ = len_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader) {
          return mergeFrom((com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader other) {
        if (other == com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getMagicNum() != 0) {
          setMagicNum(other.getMagicNum());
        }
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getLen() != 0) {
          setLen(other.getLen());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <code>uint32 version = 1;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>uint32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int magicNum_ ;
      /**
       * <code>uint32 magic_num = 2;</code>
       * @return The magicNum.
       */
      @java.lang.Override
      public int getMagicNum() {
        return magicNum_;
      }
      /**
       * <code>uint32 magic_num = 2;</code>
       * @param value The magicNum to set.
       * @return This builder for chaining.
       */
      public Builder setMagicNum(int value) {
        
        magicNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 magic_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagicNum() {
        
        magicNum_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ ;
      /**
       * <code>uint32 cmd = 3;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>uint32 cmd = 3;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cmd = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int len_ ;
      /**
       * <code>uint32 len = 4;</code>
       * @return The len.
       */
      @java.lang.Override
      public int getLen() {
        return len_;
      }
      /**
       * <code>uint32 len = 4;</code>
       * @param value The len to set.
       * @return This builder for chaining.
       */
      public Builder setLen(int value) {
        
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 len = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLen() {
        
        len_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bayss.common.netty.proto.MessageeHeader)
    }

    // @@protoc_insertion_point(class_scope:com.bayss.common.netty.proto.MessageeHeader)
    private static final com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader();
    }

    public static com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageeHeader>
        PARSER = new com.google.protobuf.AbstractParser<MessageeHeader>() {
      @java.lang.Override
      public MessageeHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageeHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageeHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageeHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bayss.common.netty.proto.ProtoMessgae.MessageeHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bayss_common_netty_proto_MessageeHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bayss_common_netty_proto_MessageeHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoMessgae.proto\022\034com.bayss.common.n" +
      "etty.proto\"\\\n\016MessageeHeader\022\017\n\007version\030" +
      "\001 \001(\r\022\021\n\tmagic_num\030\002 \001(\r\022\013\n\003cmd\030\003 \001(\r\022\013\n" +
      "\003len\030\004 \001(\r\022\014\n\004data\030\005 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bayss_common_netty_proto_MessageeHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bayss_common_netty_proto_MessageeHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bayss_common_netty_proto_MessageeHeader_descriptor,
        new java.lang.String[] { "Version", "MagicNum", "Cmd", "Len", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
